### ISSUE TITLE
Config file ???

### ISSUE THREAD

**Issue by burabaika** [hydrotho/Telegram_qBittorrent_Notifier#1]
Hello!

Where should i put config file and what name of it???
So strange readme without the most important thing - where to put the config and in what form to enter the token - with botXXXXXXXXXXX or just XXXXXXXXXXXXXX

![Снимок](https://github.com/user-attachments/assets/a608b5d6-5d27-4eed-aee6-38e34d6b5467)

**Comment by hydrotho** [comment]
Most CLI applications typically implement a `--help` flag. You can use `Telegram_qBittorrent_Notifier --help` to get more information. Below is the output I obtained when running this command on a Linux server:

```
❯ Telegram_qBittorrent_Notifier --help
NAME:
   Telegram_qBittorrent_Notifier - A simple CLI tool for qBittorrent that sends a notification to Telegram chat via bot on torrent finished

USAGE:
   Telegram_qBittorrent_Notifier [global options] command [command options]

VERSION:
   1.1.2

COMMANDS:
   send     Send a notification with provided torrent information
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --config FILE  Load configuration from FILE (default: "/root/.config/Telegram_qBittorrent_Notifier/config.yaml")
   --help, -h     show help
   --version, -v  print the version

   Telegram

   --telegram-bot-token BOT_TOKEN  Telegram BOT_TOKEN for sending notifications (default: N/A)
   --telegram-chat-id CHAT_ID      Telegram CHAT_ID to receive notifications (default: N/A)
```

Regarding the format of the `telegram-bot-token`, I believe the token provided by Telegram's [@BotFather](https://t.me/BotFather) does not include the `bot` prefix that you mentioned.

**Comment by burabaika** [comment]
okay
add file config.yaml
go t odirectory with script
make command Telegram_qBittorrent_Notifier.exe --config config.yaml
and get nothing
![Снимо222к](https://github.com/user-attachments/assets/0b7fce8b-f99d-4b9a-a0a0-7d7d90964042)

**Comment by burabaika** [comment]
oh, it works
just dont say nothing if import was succesful
